stages:
  - build
  - deploy

validate-voevents:
  stage: build
  image: debian:stable-slim
  script:
    - apt-get update
    - apt-get -y install --no-install-recommends libxml2-utils curl
    - curl -O http://www.ivoa.net/xml/VOEvent/VOEvent-v2.0.xsd
    - echo 99ba1e3b8351a6f792a2499d3acc70695898ae82588165b6599712a85df1a795  VOEvent-v2.0.xsd > hash
    - sha256sum --check hash
    - xmllint --schema VOEvent-v2.0.xsd _static/*.xml

build:
  stage: build
  image: python:slim
  variables:
    SPHINXOPTS: -W
  script:
    - pip install -r requirements.txt
    - sphinx-build -M html . _build
  artifacts:
    paths:
      - _build/html

pages:
  stage: deploy
  script:
    - mv _build/html public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - tags
  dependencies:
    - build
